In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

In [2]:
driver=webdriver.Chrome(r'E:/chromedriver')
driver.get("https://www.amazon.in/")
driver.maximize_window()

In [3]:
item=driver.find_element_by_id('twotabsearchtextbox')
item.send_keys('Samsung Phones')
search=driver.find_element_by_id('nav-search-submit-button')
search.click()

In [4]:
name=[]
try:
    pname=driver.find_elements_by_xpath('//span[@class="a-size-medium a-color-base a-text-normal"]')
    for phone in pname:
         name.append(phone.text)
except:
        name.append('-')
print(name)

['Samsung Galaxy M12 (White,4GB RAM, 64GB Storage) 6000 mAh with 8nm Processor | True 48 MP Quad Camera | 90Hz Refresh Rate', 'Samsung Galaxy M51 (Electric Blue, 6GB RAM, 128GB Storage)', 'Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB Storage)', 'Samsung Galaxy M31 (Space Black, 6GB RAM, 128GB Storage)', 'Samsung Galaxy M11 (Black, 4GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers', 'Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage) 6000 mAh with 8nm Processor | True 48 MP Quad Camera | 90Hz Refresh Rate', 'Samsung Galaxy M02 (Blue,3GB RAM, 32GB Storage)', 'Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64GB Storage)', 'Samsung Galaxy M01 Core (Black, 2GB RAM, 32GB Storage) with No Cost EMI/Additional Exchange Offers', 'Samsung Galaxy M31 (Ocean Blue, 8GB RAM, 128GB Storage)', 'Samsung Galaxy M31 (Space Black, 6GB RAM, 64GB Storage)', 'Samsung Galaxy M11 (Violet, 4GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers', 'Samsung Galaxy M31s (Mirage Blue, 6GB RAM, 128GB Storage)', 'Samsung Galaxy M21 (Raven Black, 4GB RAM, 64GB Storage)', 'Samsung Galaxy M12 (Black,6GB RAM, 128GB Storage) 6000 mAh with 8nm Processor | True 48 MP Quad Camera | 90Hz Refresh Rate', 'Samsung Galaxy M02s (Black,3GB RAM, 32GB Storage) | 5000 mAh | Triple Camera', 'Samsung Galaxy M12 (Blue,6GB RAM, 128GB Storage) 6000 mAh with 8nm Processor | True 48 MP Quad Camera | 90Hz Refresh Rate', 'Samsung Galaxy M51 (Celestial Black, 8GB RAM, 128GB Storage)', 'Samsung Galaxy M12 (White,6GB RAM, 128GB Storage) 6000 mAh with 8nm Processor | True 48 MP Quad Camera | 90Hz Refresh Rate', 'Samsung Galaxy M12 (Black,4GB RAM, 64GB Storage) 6000 mAh with 8nm Processor | True 48 MP Quad Camera | 90Hz Refresh Rate', 'Mi 10T Pro 5G (Cosmic Black, 8GB RAM, 128GB Storage) -|Alexa Hands-Free Capable | Additional Exchange/No Cost EMI Offers', 'Samsung Galaxy M11 (Black, 4GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers']

In [5]:
price=[]
try:
    pprice=driver.find_elements_by_xpath('//span[@class="a-price-whole"]')
    for p in pprice:
        price.append(p.text)
except:
    price.append('-')
print(price)

['9,999', '9,999', '9,999', '9,999', '20,999', '14,999', '14,999', '8,999', '9,999', '7,299', '12,499', '6,199', '16,999', '15,999', '8,999', '16,999', '12,499', '12,499', '8,999', '12,499', '22,999', '12,499', '9,999', '37,999', '8,999']

In [12]:
import pandas as pd
finallist=zip(name,price)
df=pd.DataFrame(finallist)
df.columns=['Mobile_Name','Mobile_Price']

In [13]:

df

                                          Mobile_Name Mobile_Price
0   Samsung Galaxy M12 (White,4GB RAM, 64GB Storag...        9,999
1   Samsung Galaxy M51 (Electric Blue, 6GB RAM, 12...        9,999
2   Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB...        9,999
3   Samsung Galaxy M31 (Space Black, 6GB RAM, 128G...        9,999
4   Samsung Galaxy M11 (Black, 4GB RAM, 64GB Stora...       20,999
5   Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage...       14,999
6     Samsung Galaxy M02 (Blue,3GB RAM, 32GB Storage)       14,999
7   Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64...        8,999
8   Samsung Galaxy M01 Core (Black, 2GB RAM, 32GB ...        9,999
9   Samsung Galaxy M31 (Ocean Blue, 8GB RAM, 128GB...        7,299
10  Samsung Galaxy M31 (Space Black, 6GB RAM, 64GB...       12,499
11  Samsung Galaxy M11 (Violet, 4GB RAM, 64GB Stor...        6,199
12  Samsung Galaxy M31s (Mirage Blue, 6GB RAM, 128...       16,999
13  Samsung Galaxy M21 (Raven Black, 4GB RAM, 64GB...       15,999
14  Samsung Galaxy M12 (Black,6GB RAM, 128GB Stora...        8,999
15  Samsung Galaxy M02s (Black,3GB RAM, 32GB Stora...       16,999
16  Samsung Galaxy M12 (Blue,6GB RAM, 128GB Storag...       12,499
17  Samsung Galaxy M51 (Celestial Black, 8GB RAM, ...       12,499
18  Samsung Galaxy M12 (White,6GB RAM, 128GB Stora...        8,999
19  Samsung Galaxy M12 (Black,4GB RAM, 64GB Storag...       12,499
20  Mi 10T Pro 5G (Cosmic Black, 8GB RAM, 128GB St...       22,999
21  Samsung Galaxy M11 (Black, 4GB RAM, 64GB Stora...       12,499

In [14]:
df.to_csv(r'C:\Users\Lenovo\Amazon_Mobiles(Selenium).csv',index=False,header=True)

In [17]:
df1=pd.read_csv('Amazon_Mobiles(Selenium).csv')

In [18]:
df1

                                          Mobile_Name Mobile_Price
0   Samsung Galaxy M12 (White,4GB RAM, 64GB Storag...        9,999
1   Samsung Galaxy M51 (Electric Blue, 6GB RAM, 12...        9,999
2   Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB...        9,999
3   Samsung Galaxy M31 (Space Black, 6GB RAM, 128G...        9,999
4   Samsung Galaxy M11 (Black, 4GB RAM, 64GB Stora...       20,999
5   Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage...       14,999
6     Samsung Galaxy M02 (Blue,3GB RAM, 32GB Storage)       14,999
7   Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64...        8,999
8   Samsung Galaxy M01 Core (Black, 2GB RAM, 32GB ...        9,999
9   Samsung Galaxy M31 (Ocean Blue, 8GB RAM, 128GB...        7,299
10  Samsung Galaxy M31 (Space Black, 6GB RAM, 64GB...       12,499
11  Samsung Galaxy M11 (Violet, 4GB RAM, 64GB Stor...        6,199
12  Samsung Galaxy M31s (Mirage Blue, 6GB RAM, 128...       16,999
13  Samsung Galaxy M21 (Raven Black, 4GB RAM, 64GB...       15,999
14  Samsung Galaxy M12 (Black,6GB RAM, 128GB Stora...        8,999
15  Samsung Galaxy M02s (Black,3GB RAM, 32GB Stora...       16,999
16  Samsung Galaxy M12 (Blue,6GB RAM, 128GB Storag...       12,499
17  Samsung Galaxy M51 (Celestial Black, 8GB RAM, ...       12,499
18  Samsung Galaxy M12 (White,6GB RAM, 128GB Stora...        8,999
19  Samsung Galaxy M12 (Black,4GB RAM, 64GB Storag...       12,499
20  Mi 10T Pro 5G (Cosmic Black, 8GB RAM, 128GB St...       22,999
21  Samsung Galaxy M11 (Black, 4GB RAM, 64GB Stora...       12,499